server:
  port: 8090

spring:
  data:
    mongodb:
      uri: "mongodb+srv://admin:admin123@cluster0.twywbtc.mongodb.net/kidlet_online_store"

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate :DEBUG




