server:
  port: 8091

spring:
  data:
    mongodb:
      uri: "mongodb+srv://admin:admin123@cluster0.twywbtc.mongodb.net/?retryWrites=true&w=majority"
      database: "kidlet_online_store"

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

#/swagger-ui/index.html
springdoc:
  swagger-ui:
    path: "/swagger-ui-custom.html"